export const USER_ORDER_REQUEST = "USER_ORDER_REQUEST";
export const USER_ORDER_SUCCESS = "USER_ORDER_SUCCESS";
export const USER_ORDER_FAIL = "USER_ORDER_FAIL";

export const ORDER_DETAIL_REQUEST = "ORDER_DETAIL_REQUEST";
export const ORDER_DETAIL_SUCCESS = "ORDER_DETAIL_SUCCESS";
export const ORDER_DETAIL_FAIL = "ORDER_DETAIL_FAIL";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const ORDER_LIST_MY_ORDERS_REQUEST = "ORDER_LIST_MY_ORDERS_REQUEST";
export const ORDER_LIST_MY_ORDERS_SUCCESS = "ORDER_LIST_MY_ORDERS_SUCCESS";
export const ORDER_LIST_MY_ORDERS_RESET = "ORDER_LIST_MY_ORDERS_RESET";
export const ORDER_LIST_MY_ORDERS_FAIL = "ORDER_LIST_MY_ORDERS_FAIL";
