export const USER_ORDER_REQUEST = "USER_ORDER_REQUEST";
export const USER_ORDER_SUCCESS = "USER_ORDER_SUCCESS";
export const USER_ORDER_FAIL = "USER_ORDER_FAIL";

export const ORDER_DETAIL_REQUEST = "ORDER_DETAIL_REQUEST";
export const ORDER_DETAIL_SUCCESS = "ORDER_DETAIL_SUCCESS";
export const ORDER_DETAIL_FAIL = "ORDER_DETAIL_FAIL";
